### ISSUE TITLE
toybox sh: test -a command fails with "too many arguments" error

### ISSUE THREAD

**Issue by iamdavidcz** [landley/toybox#376]
Option `-a` is probably not from [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html), but it does the same what `-e` does:
> Returns true if file exists. Does the same thing as -e. Both are included for compatibility reasons with legacy versions of Unix.

but it fails with `too many arguments` error.

Tested on both `x86_64`:
```
$ ./toybox-x86_64 sh -c "test -a hello.c"
test: too many arguments
```
and `aarch64`:
```
$ ./toybox-aarch64 sh -c "test -a hello.c"
test: too many arguments
```

It effectively prevents from building GNU Make 4.3 on `./configure` step.
@landley It is possible to add support for this option for compatibility reasons?

**Comment by landley** [comment]
> Option -a is probably not from [POSIX]

No, posix has -a and -o mean "and" and "or", which we've implemented.

That said, I see it there in bash's "help test" meaning different things based on context. Sigh.

Commit 7b9fb3ba4da0

**Comment by iamdavidcz** [comment]
@landley
Thank you for a quick fix, sir. However, I'm still not able to build GNU Make 4.3 using `toybox sh`. `configure` script from GNU Make 4.3 makes a bunch of weird checks in order to gain a grasp of what are the capabilities of the given shell. The most problematic one for `toybox sh` is:
```
as_required="as_fn_return () { (exit \$1); }
as_fn_success () { as_fn_return 0; }
as_fn_failure () { as_fn_return 1; }
as_fn_ret_success () { return 0; }
as_fn_ret_failure () { return 1; }

exitcode=0
as_fn_success || { exitcode=1; echo as_fn_success failed.; }
as_fn_failure && { exitcode=1; echo as_fn_failure succeeded.; }
as_fn_ret_success || { exitcode=1; echo as_fn_ret_success failed.; }
as_fn_ret_failure && { exitcode=1; echo as_fn_ret_failure succeeded.; }
if ( set x; as_fn_ret_success y && test x = \"\$1\" ); then :

else
  exitcode=1; echo positional parameters were not saved.
fi
test x\$exitcode = x0 || exit 1
test -x / || exit 1"

  if (eval "$as_required") 2>/dev/null; then :
  as_have_required=yes
else
  as_have_required=no
fi
```

I've tried to run this script manually with `toybox sh` and the output is the following:
```
as_fn_failure succeeded.
sh: return: No such file or directory
as_fn_ret_success failed.
sh: return: No such file or directory
sh: return: No such file or directory
positional parameters were not saved.
```

The overall result is the following message from the `configure` script.
```
configure: This script requires a shell more modern than all                                                                                                                            
configure: the shells that I found on your system.                                          
configure: Please tell bug-autoconf@gnu.org and bug-make@gnu.orgconfigure: about your system, including any error possibly output configure: before this message. Then install a modern shell, or configure: manually run the script under such a shell if you do configure: have one.
```
Anyway, I'm going to give BusyBox `ash` a try.

**Comment by landley** [comment]
Yeah, there's a whole whack-a-mole process of going through package builds' configure steps and tracking down each deviation to either greenlight or fix. I spent years and years doing that (the stuff before https://landley.net/notes-2005.html#16-03-2005 would be in my old landley.livejournal.com which... is that even up anymore what with Russia and all?)

Before I did toybox I spent several years making BusyBox build Linux From Scratch, and eventually got it to complete successfully building version 6.7. Alas, toysh isn't quite there yet, and I haven't implemented "awk" yet, and you need a patch to remove the kernel's "bc" dependency, and the kernel grew lex and yacc dependencies in autoconf...

It's on the todo list, but not there yet. Building Linux From Scratch under toybox (via https://landley.net/toybox/faq.html#mkroot) is pretty much my 1.0 release goal.

**Comment by landley** [comment]
Initial issue seems addressed, open new ones for new topics.
